# Generated by Django 5.0.3 on 2024-04-26 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_auth.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('library', 'Library'), ('hostel', 'Hostel'), ('alumni', 'Alumni'), ('security', 'Security'), ('school_fees', 'School Fees'), ('faculty_dues', 'Faculty Dues'), ('convocation_levy', 'Convocation Levy'), ('audit', 'audit')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('feedback', models.CharField(blank=True, max_length=1000, null=True)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.clearance')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='student_clearance_fiels')),
                ('clearance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.clearanceitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clearanceitem',
            constraint=models.UniqueConstraint(models.F('name'), models.F('clearance'), name='Clearance item unique for each clearance'),
        ),
    ]
